#!/usr/bin/env bash

#
# Config
# See permitted scopes here - https://sandbox-api.va.gov/oauth2/health-insurance/v1/.well-known/openid-configuration
#
test -n CLIENT_ID
test -n CLIENT_SECRET
SCOPES="system/Appointment.read system/Patient.read"
#
# Create assertion
#
CLIENT_ASSERTION=$(docker run --rm lighthouse-auth-utils:latest \
  client_secret_jwt \
  -c $CLIENT_ID \
  -s $CLIENT_SECRET \
  -a "https://deptva-eval.okta.com/oauth2/aus8nm1q0f7VQ0a482p7/v1/token")

echo "Assertion: $(echo $CLIENT_ASSERTION | jq .)"

CLIENT_ASSERTION=$(echo $CLIENT_ASSERTION | jq -r '.token')

#
# Fetch a token
#
curl -X POST \
  --header "accept: application/json" \
  --header "content-type: application/x-www-form-urlencoded" \
  -d "grant_type=client_credentials&client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer&client_assertion=${CLIENT_ASSERTION}&scope=${SCOPES}" \
  https://sandbox-api.va.gov/oauth2/health-insurance/v1/token
